# FIX COLOR (QUAN TRỌNG)
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# split dễ
unbind '"'
unbind %

bind | split-window -h
bind - split-window -v

# mouse
set -g mouse on

# vim mode
setw -g mode-keys vi

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
source-file ~/.tokyonight_storm.tmux

run '~/.tmux/plugins/tpm/tpm'
